eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-user:zaq12wsx@bangvmpltesappsrv.sapient.com:10001/eureka/
  instance:
    prefer-ip-address: true
    homePageUrlPath: /sales
    healthCheckUrlPath: /health
    appname: ${spring.application.name}-${api.version}
    virtual-host-name: ${spring.application.name}-${api.version}

logging:
 level:
  feign: DEBUG
  
spring:
 mvc:
  view:
   prefix: /WEB-INF/views/
   suffix: .jsp
server.port: 8080
node.server.url: http://bangvmpltesappsrv.sapient.com:3000
      
