eureka:
 client:
  serviceUrl:
   defaultZone: http://eureka-user:zaq12wsx@bangvmpltesappsrv.sapient.com:10001/eureka/
  healthcheck: 
   enabled: true

logging:
 level:
  feign: DEBUG
  
spring:
 mvc:
  view:
   prefix: /WEB-INF/jsp/
   suffix: .jsp

server.port: 80
      
