couchbase:
 host: bangvmpltescouchdb.sapient.com
 bucketName: microservices
 bucketConnectionTimeout: 15
server:
 port: 0
spring:
  jersey:
    application-path: /${api.version}
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-user:zaq12wsx@bangvmpltesappsrv.sapient.com:10001/eureka/
  instance:
    prefer-ip-address: true
    homePageUrlPath: /${api.version}/bids
    healthCheckUrlPath: /health
    appname: ${spring.application.name}-${api.version}
    virtual-host-name: ${spring.application.name}-${api.version}
